Feature/implement auth
danielursu/goooplanner-client pull request #8
Opened 2024-08-12 09:12 UTC by pvictordev

2024-08-12 11:39 UTC, danielursu requested changes

2024-08-12 11:39 UTC, danielursu commented on src/app/components/auth/login/login.component.html
> +					<small class="p-error"> Please enter a valid email address. </small>
check the indentation rules for @if, @for etc. It should have a tab in front of the line

2024-08-12 11:39 UTC, danielursu commented on src/app/components/auth/login/login.component.html
> +				<span> Do not have an account ? <a [routerLink]="['/register']">Register</a></span>
leave empty lines for each tag for better readability

2024-08-12 11:39 UTC, danielursu commented on src/app/components/auth/login/login.component.ts
> +import { AuthService } from "src/app/services/auth.service";
there is a convention that the 3rd party import to be the first and imports from project's context to be the second separated by an empty lines
```suggestion
import { HttpClient } from "@angular/common/http";

import { AuthService } from "src/app/services/auth.service";
```

2024-08-12 11:39 UTC, danielursu commented on src/app/components/auth/login/login.component.ts
> +	login() {
let's start to add access modifiers and return type for all the methods in the app and 
```suggestion
	private login(): void {
```

2024-08-12 11:39 UTC, danielursu commented on src/app/components/calendar/calendar.component.ts
> +	userData: any;
what data do you get?

2024-08-12 11:39 UTC, danielursu commented on src/app/guards/auth.guard.ts
> +// auth.guard.ts
```suggestion

```

2024-08-12 11:39 UTC, danielursu commented on src/app/guards/auth.guard.ts
> +import { AuthService } from "../services/auth.service";
```suggestion
import { CanActivate, Router } from "@angular/router";

import { AuthService } from "../services/auth.service";
```

2024-08-27 09:18 UTC, danielursu requested changes

2024-08-27 09:18 UTC, danielursu commented on src/app/services/auth.service.ts
> +			}
```suggestion
			return currentTime > tokenExpire;
```
trick

2024-08-27 09:18 UTC, danielursu commented on src/app/guards/auth.guard.ts
> +		private router: Router,
```suggestion
		private readonly authService: AuthService,
		private readonly router: Router,
```
best practice for injecting services
please add readonly in each injecting constructors

2024-08-27 09:18 UTC, danielursu commented on src/app/components/calendar/calendar.component.ts
> +	private getRandomColor(): string {
```suggestion
	}
	
	private getRandomColor(): string {
```

2024-08-27 09:18 UTC, danielursu commented on src/app/components/calendar/calendar.component.ts
> +		if (!this.userData || !this.userData.firstName || !this.userData.lastName) {
add in this method a console.log("getInitials()") and open Web Console. Count how many of getInitials() calls are in this component. 
This is a performance issue. The best approach is "never call a method from ts directly, create instead a pure pipe and move the logic there". If you need hints, please let me know

2024-08-27 09:18 UTC, danielursu commented on src/app/guards/auth.guard.ts
> +		private router: Router,
also there is a newer approach to inject services. You can use it that way, it's modern
private readonly authService = inject(AuthService);

2024-08-27 10:06 UTC, pvictordev commented on src/app/components/calendar/calendar.component.ts
> +	private getRandomColor(): string {
I did not understand this change request, can I have additional comments ?

2024-08-27 11:07 UTC, pvictordev commented on src/app/components/calendar/calendar.component.ts
> +	private getRandomColor(): string {
Do you mean by this change to avoid the circular dependency issue ?

2024-08-27 11:18 UTC, danielursu commented on src/app/components/calendar/calendar.component.ts
> +	private getRandomColor(): string {
just empty line between the methods

2024-08-27 11:24 UTC, danielursu approved these changes

2024-08-27 12:14 UTC, merged